### ISSUE TITLE
[RoadMap]

### ISSUE THREAD

**Issue by YichengDWu** [YichengDWu/tinyedm#1]
- [x] Add EMA (#4 )
- [ ] Add FID logging
- [ ] Add guidance (not so important)
- [x] improved edm (#6 )
- [ ] Post-hoc EMA
